### ISSUE TITLE
Проблема с кириллицей (?) при фильтрации

### ISSUE THREAD

**Issue by mbvyd** [maxim-uvarov/PQYandexMetrica#3]
Для фильтрации если указываю `ym:s:regionCityName=='Москва'`, то данные фильтруются корректно.
Но в случае `ym:s:lastsignSearchEngineRoot=.('Яндекс','Google')`, фильтруется только Гугл. А если `ym:s:lastsignSearchEngineRoot=='Яндекс'`, тогда вообще выдаёт null. При этом, без фильтрации Яндекс виден в отчёте. Пробовал закодировать слово Яндекс в `%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81`, но данные также не фильтруются.
Кто-нибудь сталкивался? Есть ли вариант побороть?

_Обновление._
Попробовал от обратного -- исключить ненужные поисковики: 
`ym:s:lastsignSearchEngineRoot!.('Mail.ru','Rambler','Yahoo!','Tut.by','DuckDuckGo')`
Отсеялись только Рамблер и Дакдакго. То есть, дело может быть и не в кириллице... А если экранировать "спецсимволы" (в данном случае, точку, воскл. знак) обратным слэшом (мало ли, может проканало бы), то выкидывает в ошибку 4003.

**Comment by ultraviolet** [comment]
Попробовал от обратного -- исключить ненужные поисковики: 
`ym:s:lastsignSearchEngineRoot!.('Mail.ru','Rambler','Yahoo!','Tut.by','DuckDuckGo')`
Отсеялись только Рамблер и Дакдакго. То есть, дело может быть и не в кириллице... А если экранировать "спецсимволы" обратным слэшом (мало ли, может проканало бы), то выкидывает в ошибку 4003.

**Comment by maxim-uvarov** [comment]
Здравствуйте! Не сталкивался. 

Если данные по `ym:s:regionCityName=='Москва'` фильтруются, значит проблема не в кириллице, мне видится.

Проверил документацию метод с метаданными, который справочник функций возвращает. Он говорит что ym:s:lastsignSearchEngineRoot вообще не должен фильтроваться...

Не знаю чем помочь, кроме как предложить спросить в чатике метрики: https://t.me/yandexmetrika

![image](https://user-images.githubusercontent.com/4896754/111114948-8ea99880-8596-11eb-8f1e-c0b72c9e947d.png)

**Comment by mbvyd** [comment]
Принято, спасибо. Решил выгружать всё, а уже потом фильтровать средствами Power Bi/Query.
